version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  web-app:
    container_name: web-app
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - "./client/src:/client/src"
    env_file:
      - "./client/.env"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  server:
    container_name: server
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
    volumes:
       - "./api/src:/api/src"
    env_file:
      - "./api/.env"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    networks:
      - app-network
volumes:
  mongodb_volume: