name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - '**'
    
jobs:

  Continuous-Integration:

    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on backend
        run: cd ./api && npm install 

      - name: Run linting check on backend
        run: cd ./api && npm run lint 

      - name: Check formatting on backend
        run: cd ./api && npm run preetier:check

      - name: Installing Dependencies on Fronetend
        run: cd ./client && npm install

      - name: Check formatting on frontend
        run: cd ./client && npm run lint

      - name: Check formatting on frontend
        run: cd ./client && npm run preetier:check
